### ISSUE TITLE
cli.set_br_password( ... ), rc = 2562

### ISSUE THREAD

**Issue by conggalam12** [innovasoft-org/libmqttcli#11]
When I set password length more than 64 and received error
cli.set_br_password( ... ), rc = 2562
Can you give me source code and I can know my error ?

**Comment by innovasoft-org** [comment]
Hi,
I am sorry for late response. Unfortunately at the moment source code could not be published.
`2562` = 0xA02, in `mqtt_common.h` file it is represented by the following constant `MQTT_INVALID_ARGS`. It means that longer passwords are rejected at the moment. It could be changed if you want.
All limitations are also present in `mqtt_common.h`.
If you have any more questions, please do no hesitate ;)
